package useless:feature@0.0.1;

interface the-useless-thing {
    do-the-useless-thing: func();
    do-another-but-equally-useless-thing: func();
}

interface argh {
    do-argh: func();
}

interface hibble-bibble {
    hibble-and-indeed-bibble: func();
}

world uselessness {
    export the-useless-thing;
    export argh;
}

//world bibbling-uselessness {
//    include uselessness;
//    export hibble-bibble;
//}
